#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/chat
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: root
#    password: test
#    schema: classpath:h2/schema-h2.sql
#    data: classpath:h2/data-h2.sql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.peter.chat.entity
chat:
  webSocket:
    port: 8090
    websocketPath: /ws
  login-interceptor:
    include:
      /**
    exclude:
      /user/registerOrLogin
  setting:
    defaultNicknameList:
      美到没朋友,逺来是你,淡淡的优雅,黑名单。,龍飛鳳ゝ舞,闹钟你别闹→_→,做個沒心沒肺菂尐女亽